specVersion: 0.3.0
name: terra-subql-starter
version: 0.0.1
runner:
  node:
    name: "@subql/node-terra"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be use as a starting point for developing your Terra based
  SubQuery project
repository: https://github.com/subquery/terra-subql-starter
schema:
  file: ./schema.graphql
network:
  chainId: columbus-5
  endpoint: https://lcd.terra.dev
  dictionary: https://api.subquery.network/sq/subquery/terra-columbus-5-dictionary
  # Optionally provide a mantlemint endpoint to further speed up processing
  mantlemint: "https://mantlemint.terra-columbus-5.beta.api.onfinality.io:1320"
dataSources:
  - kind: terra/Runtime
    startBlock: 7428356
    mapping:
      file: ./dist/index.js
      handlers:
        #- handler: handleBlockMessage
        #  kind: terra/BlockHandler
        #  filter:
        #    type: /terra.wasm.v1beta1.MsgExecuteContract
        #    values:
        #      contract: terra1jfuq655fmqp7uhkkqanmljqj26r9acs68drn2s
        - handler: handleTransactionMessage
          kind: terra/TransactionHandler
          filter:
            type: /terra.wasm.v1beta1.MsgExecuteContract
            values:
              contract: terra1jfuq655fmqp7uhkkqanmljqj26r9acs68drn2s
